name: API CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development] 

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4 # Corregido el nombre de la organización

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Corregido el nombre de la organización
        with:
          node-version: '14.x' # Corregido el formato y versión de Node.js

      - name: Install Dependencies
        run: npm install

      - name: Run unit and integrate tests
        run: npm run test

      #- name: Run code linter
      #  run: npm run lint
